name: Check images

on:
  workflow_dispatch:

env:
  BOT_NAME: nr-opensource-bot
  BOT_EMAIL: opensource+bot@newrelic.com

jobs:
  check-images:
    name: Convert to WebP/Remove unused
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: develop
          persist-credentials: false

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn add glob10@npm:glob@^10.0.0 meow@11.0.0 webp-converter@2.3.3

      -name: test logs
        run: yarn test-workflow-comment